// <auto-generated />
namespace Garage2._0._1.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class noboat : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(noboat));
        
        string IMigrationMetadata.Id
        {
            get { return "201806140338548_noboat"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
